### ISSUE TITLE
Theme broken after recent TTRSS update

### ISSUE THREAD

**Issue by ivantomica** [hpsu/ttrss-breeze-theme#3]
After recent update to TTRSS (to version 17.12) it would seem like theme is broken. Are you planning on updating it?

**Comment by flappysquirrel** [comment]
https://github.com/levito/tt-rss-feedly-theme/issues/51#issuecomment-352249163

**Comment by ivantomica** [comment]
I'm not quite sure how this exactly is relevant, is theme based on feedly theme? Looking at CSS they don't look similar at all except structure that TTRSS requires. I'm aware of changes TTRSS made but not sure how to fix them or how does that linked issue help.

**Comment by flappysquirrel** [comment]
Sorry, I linked that post because apparently most of the themes were broken in a similar way.

Following that, the theme appears on screen and is largely usable; however, the icons are missing.

These are the steps I took:

1) open up `tt-rss/themes/breeze-light.css`

2) change the version number in the first line from 17.4 to 17.12

3) paste this at the end of the file:

```
body.ttrss_main,
body.ttrss_prefs,
#main {
  position : absolute;
  width: 100%;
  height: 100%;
  border: 0;
  padding: 0;
  margin: 0;
}
```

Again, credit to Gravemind.

**Comment by ivantomica** [comment]
Thank you for the information. This made this great time usable again. Will you update it soon perhaps in order to fully support new version?

**Comment by ivantomica** [comment]
Latest update resolved the issue. Thank you.
